### PR TITLE
breaking: Remove dependency on streams polyfill

### LINKED ISSUE #135: Possibility to remove web-streams-polyfill dependency?
`web-streams-polyfill` is used as a dependency of this package, which is only used in [streams.cjs](https://github.com/node-fetch/fetch-blob/blob/f077471a23ee26867e0a1c96f5a846099d6da0c7/streams.cjs) as a polyfill fallback for users in \<v16.5.0 for `ReadableStream`s.

However, I personally find it extremely overblown that, in this case, we're pulling a \>7 MB dependency for something that might or might not be used, while we're also not using all the available po(l/n)yfills but `ponyfill.es2018.js`, which considerably (outside of depending of an external package) increases the size of the dependants, such as `node-fetch`.

Is it possible to include this file inside `fetch-blob`, or take any other possible solution (while also keeping compatibility with older Node.js versions)? I understand this is relatively low-priority, but I thought I'd at least raise it up for consideration.

### PR DESCRIPTION
**Pull request by jimmywarting**
## The purpose of this PR is:
- To remove the dependency on web streams polyfill
- Update LTS supported NodeJS version as to use web streams directly from NodeJS instead
- bump engines.node to >=16.7 (16.5 received web streams... 16.7 got buffer.Blob.stream() included)
- remove CHANGELOG.md and instead start using github releases to craft new changes based on merged PRs

-------------------------------------------------------------------------------------------------

- [x] I prefixed the PR-title with `docs: `, `fix(area): `, `feat(area): ` or `breaking(area): `
- [x] I updated the README.md
- [x] I Added unit test(s)

-------------------------------------------------------------------------------------------------

- fix #116
- fix #135

### CODE REVIEW

**Comment by jimmywarting** [comment]
This http loader is for sure getting a bit annoying...
thinking of removing it completely.

**Comment by jimmywarting** [comment]
ping @LinusU

**Comment by gr2m** [comment]
How are releases created?

**Comment by jimmywarting** [comment]
there is no automated flow in this repo

**Pull request merged**
